=== indzhrih/IP/SpringXMLParser/src/main/resources/data/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="borrowedBooks">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="borrowedBook" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="bookId" type="xs:int" use="required"/>
                                                <xs:attribute name="issueDate" type="xs:date" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="username" type="xs:string" use="required"/>
                        <xs:attribute name="password" type="xs:string" use="required"/>
                        <xs:attribute name="role" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="LIBRARIAN"/>
                                    <xs:enumeration value="READER"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== indzhrih/IP/SpringXMLParser/src/main/resources/data/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
  <user password="librarian" role="LIBRARIAN" username="librarian">
    <borrowedBooks/>
  </user>
  <user password="reader1" role="READER" username="reader1">
    <borrowedBooks>
      <borrowedBook bookId="16" issueDate="2025-12-09"/>
      <borrowedBook bookId="17" issueDate="2025-12-09"/>
    </borrowedBooks>
  </user>
  <user password="qwertyY1" role="READER" username="log">
    <borrowedBooks/>
  </user>
</users>
